version: "3"
services:
    app:
        build: .
        env_file:
            - .env
        ports:
            - "8501:8501"
        volumes:
            - ./src:/app/src
        networks:
            - app-network
        command: poetry run streamlit run main.py

networks:
    app-network:
        driver: bridge